### ISSUE TITLE
Symbol not found: _cusparseGetErrorString

### ISSUE THREAD

**Issue by Chenng** [TomHeaven/pytorch-osx-build#11]
The CUDA Version is 10.1.105 and GPU Driver Version is  387.10.10.10.40.105.
I have installed torch-1.6.0-cp37-cp37m-macosx_10_13_x86_64.whl, but when I use ``import torch`` , I have got an error that:

```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/**/.pyenv/versions/3.7.0/lib/python3.7/site-packages/torch/__init__.py", line 189, in <module>
    from torch._C import *
ImportError: dlopen(/Users/**/.pyenv/versions/3.7.0/lib/python3.7/site-packages/torch/_C.cpython-37m-darwin.so, 2): Symbol not found: _cusparseGetErrorString
  Referenced from: /Users/**/.pyenv/versions/3.7.0/lib/python3.7/site-packages/torch/lib/libtorch_cuda.dylib
  Expected in: /usr/local/cuda/lib/libcusparse.10.dylib
 in /Users/**/.pyenv/versions/3.7.0/lib/python3.7/site-packages/torch/lib/libtorch_cuda.dylib
```

**Comment by Chenng** [comment]
I have tried in python3.7 and python 3.7.8. 
The Mac OS version is 10.13.6 and XCode version is 10.1

**Comment by Nosskirneh** [comment]
I get something similar. Also running 10.13.6 with Xcode 10.1.

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-a16f98abca18> in <module>
----> 1 import torch

~/opt/anaconda3/lib/python3.7/site-packages/torch/__init__.py in <module>
    187     if USE_GLOBAL_DEPS:
    188         _load_global_deps()
--> 189     from torch._C import *
    190 
    191 # Appease the type checker; ordinarily this binding is inserted by the

ImportError: dlopen(/Users/xyz/opt/anaconda3/lib/python3.7/site-packages/torch/_C.cpython-37m-darwin.so, 2): Symbol not found: _cusparseCreateCoo
  Referenced from: /Users/xyz/opt/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_cuda.dylib
  Expected in: /Developer/NVIDIA/CUDA-10.0/lib/libcusparse.10.dylib
 in /Users/xyz/opt/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_cuda.dylib
```

**Comment by TomHeaven** [comment]
I compiled Pytorch 1.6 using CUDA Toolkit 10.1.243. Maybe update your CUDA Toolkit by [cuda_10.1.243_mac.dmg](http://developer.download.nvidia.com/compute/cuda/10.1/Prod/local_installers/cuda_10.1.243_mac.dmg) will solve the issue.

**Comment by Chenng** [comment]
I have upgrade the CUDA using cuda_10.1.243_mac.dmg  , and get CUDA Driver Version: 418.243 and GPU Driver Version: 387.10.10.10.40.105. But got the same error:
```
ImportError: dlopen(/Users/xxx/.pyenv/versions/3.7.8/lib/python3.7/site-packages/torch/_C.cpython-37m-darwin.so, 2): Symbol not found: _cusparseGetErrorString
  Referenced from: /Users/xxx/.pyenv/versions/3.7.8/lib/python3.7/site-packages/torch/lib/libtorch_cuda.dylib
  Expected in: /usr/local/cuda/lib64/libcusparse.10.dylib
 in /Users/xxx/.pyenv/versions/3.7.8/lib/python3.7/site-packages/torch/lib/libtorch_cuda.dylib
```

I have tried uninstall python and torch library before I reinstall pytorch, but it seems useless.

Thanks a lot.

**Comment by TomHeaven** [comment]
Try the following command:
```
sudo ln -s /usr/local/cuda/lib /usr/local/cuda/lib64
```
The torch library is looking for `libcusparse.10.dylib` in `/usr/local/cuda/lib64`, which does not exist on macOS by default.

**Comment by Chenng** [comment]
Thanks a lot. 
In fact, I have tried ``sudo cp -r  /usr/local/cuda/lib /usr/local/cuda/lib64`` , but it does not work.

Now it looks fine. Sorry for the mistake.
