### ISSUE TITLE
can't build pytorch on osx 10.13.6 for pytorch 1.5 and 1.6

### ISSUE THREAD

**Issue by llv22** [TomHeaven/pytorch-osx-build#14]
@TomHeaven 想问一下，下面的编译问题是如何解决的
我的系统环境
OSX 10.13.6
Xcode 10.1
cuda 10.1 (10.1 update2)
cudnn 7.6.5

从官方checkout pytorch 1.5和1.6源代码，都打了你的patch，如下命令编译:
```bash
MAGMA_HOME="/usr/local/lib/magma-cu101" MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ USE_OPENMP=OFF USE_QNNPACK=OFF USE_NNPACK=OFF  USE_MKLDNN=OFF USE_FBGEMM=OFF  USE_PYTORCH_QNNPACK=OFF python setup.py bdist_wheel
```
遇到如下链接问题:
```bash
[2922/3846] Linking CXX shared library lib/libtorch_cpu.dylib
FAILED: lib/libtorch_cpu.dylib 
Undefined symbols for architecture x86_64:
  "__cvtu32_mask16", referenced from:
      _xnn_f32_clamp_ukernel__avx512f in libXNNPACK.a(avx512f.c.o)
      _xnn_f32_dwconv_ukernel_up16x25__avx512f in libXNNPACK.a(up16x25-avx512f.c.o)
      _xnn_f32_dwconv_ukernel_up16x4__avx512f in libXNNPACK.a(up16x4-avx512f.c.o)
      _xnn_f32_dwconv_ukernel_up16x9__avx512f in libXNNPACK.a(up16x9-avx512f.c.o)
      _xnn_f32_gemm_ukernel_1x16__avx512f_broadcast in libXNNPACK.a(1x16-avx512f-broadcast.c.o)
      _xnn_f32_gemm_ukernel_7x16__avx512f_broadcast in libXNNPACK.a(7x16-avx512f-broadcast.c.o)
      _xnn_f32_hswish_ukernel__avx512f_x32 in libXNNPACK.a(avx512f-x32.c.o)
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 744, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "/Users/llv23/Documents/05_machine_learning/dl_gpu_mac/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/Users/llv23/Documents/05_machine_learning/dl_gpu_mac/pytorch/tools/setup_helpers/cmake.py", line 339, in build
    self.run(build_args, my_env)
  File "/Users/llv23/Documents/05_machine_learning/dl_gpu_mac/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/Users/llv23/opt/miniconda3/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
```
我上网查了一下clang的输出符号，加上https://github.com/pytorch/pytorch/issues/34451 and https://github.com/google/XNNPACK/blob/master/src/xnnpack/intrinsics-polyfill.h#L36 的XNNPACK源代码
好像原因是xcode10.1，macOSX 10.13.6的clang没有__cvtu32_mask16，囧了

想请教下兄弟怎么避开这个坑的：感觉除了XNNPACK往前回退版本，好像没别的路了；升级xcode和macOSX不现实，怕以后都没法crack了

谢谢了，盼回

**Comment by llv22** [comment]
already fix the issue, fix mentioned in https://github.com/pytorch/pytorch/issues/46803 and https://github.com/google/XNNPACK/issues/1081.
